spring:
  datasource:
    url: jdbc:postgresql://${DB_PROD_HOST}:${DB_PROD_PORT}/${DB_PROD_NAME}
    username: ${DB_PROD_USERNAME}
    password: ${DB_PROD_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create