# Tomcat
server:
  port: ${SHOP_LINK_PORT}

# Spring
spring:
  config:
    import:
      - optional:file:env.yml
  thymeleaf:
    cache: false
  web:
    resources:
      static-locations: classpath:/static/
  application:
    # Application Name
    name: slink
    profiles:
      active: ${PROFILE}
    flyway:
      sql-migration-prefix: V
      sql-migration-separator: __
      sql-migration-suffixes: .sql
      locations: classpath:db/postgres
      enabled: true
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
logging:
  level:
    org.springframework: INFO
    com.example.linkaggregator: DEBUG